# - name: common things
#   hosts: all
#   remote_user: User01
#   become: true
#   roles: 
#     - common

tasks:
- name: install and start mysql
  hosts: mysql
  remote_user: User01
  become: true
  roles: 
    - mysql

- name: install and start apache, php, ftp (vsftpd)
  hosts: web
  remote_user: User01
  become: true
  roles:
    - web  

handlers:
- name: reload apache
    service:
    name: apache2
    state: restarted