##### MYSQL #####

- name: install and start mysql
  apt:
    name: mysql-server
    update-cache: yes
  
- name: starting mysql  
  service: 
    name: mysql
    state: started

- name: enable mysql
  service:
    name: mysql
    enabled: yes

- name: Adds Python MySQL support on Debian/Ubuntu
  apt: pkg="python-mysqldb" state=present
  when: ansible_os_family == 'Debian'

- mysql_user:
    name: Wordpress_01
    password: root
    priv: '*.*:ALL'
    state: present
    